const state={newTab:localStorage.getItem('venture.newTab')==='true',theme:localStorage.getItem('venture.theme')||'system'};
const $=id=>document.getElementById(id);
const homeView=$('homeView'),resultsView=$('resultsView'),searchInput=$('searchInput'),resultsInput=$('resultsInput'),resultsList=$('resultsList'),resultStatus=$('resultStatus'),resultError=$('resultError'),fallbackLink=$('fallbackLink'),themeToggle=$('themeToggle'),resultsThemeToggle=$('resultsThemeToggle'),settingsDialog=$('settingsDialog'),newTabToggle=$('newTabToggle');
function applyTheme(){const dark=state.theme==='dark'||(state.theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.dataset.theme=dark?'dark':'light';const glyph=dark?'☀':'◐';themeToggle.textContent=glyph;if(resultsThemeToggle)resultsThemeToggle.textContent=glyph}
function cycleTheme(){state.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';localStorage.setItem('venture.theme',state.theme);applyTheme()}
function looksLikeURL(v){return /^[a-zA-Z][a-zA-Z\d+.-]*:\/\//.test(v)||/^(localhost|127\.0\.0\.1)(:\d+)?(\/.*)?$/.test(v)||/^[^\s]+\.[^\s]+(\/.*)?$/.test(v)}
function openDirectURL(v){let u=v;if(!/^[a-zA-Z][a-zA-Z\d+.-]*:\/\//.test(u))u=/^(localhost|127\.0\.0\.1)/.test(u)?`http://${u}`:`https://${u}`;location.href=u}
function showResults(q){homeView.hidden=true;resultsView.hidden=false;resultsInput.value=q;document.title=`${q} - Venture`}
function resultCard(r){const a=document.createElement('article');a.className='result-card';const l=document.createElement('a');l.href=r.url;if(state.newTab){l.target='_blank';l.rel='noopener noreferrer'}const d=document.createElement('div');d.className='result-domain';try{const u=new URL(r.url);d.textContent=(r.domain||u.hostname.replace(/^www\./,''))+'  ›  '+u.pathname.split('/').filter(Boolean).slice(0,2).join(' › ')}catch{d.textContent=r.url}const t=document.createElement('h2');t.textContent=r.title||r.url;const s=document.createElement('p');s.textContent=r.description||'';l.append(d,t,s);a.append(l);return a}
async function updateStats(){try{const r=await fetch('/api/stats',{cache:'no-store'});if(!r.ok)throw 0;const d=await r.json(),n=Number(d.indexed||0),domains=Number(d.domains||0),queued=Number(d.queued||0);$('#indexBadge').classList.add('online');$('#indexBadge span').textContent=`${n.toLocaleString()} indexed`;$('#homeIndexCount').textContent=`${n.toLocaleString()} pages indexed`;$('#homeIndexDetail').textContent=`across ${domains.toLocaleString()} domains · ${queued.toLocaleString()} queued`}catch{$('#indexBadge').classList.remove('online');$('#indexBadge span').textContent='offline';$('#homeIndexCount').textContent='Crawler offline';$('#homeIndexDetail').textContent=''}}
async function ventureResults(q){const r=await fetch(`/api/search?q=${encodeURIComponent(q)}`);if(!r.ok)throw Error(r.status);return r.json()}
async function fallbackResults(q){const r=await fetch(`/api/fallback?q=${encodeURIComponent(q)}`);if(!r.ok)throw Error(r.status);return r.json()}
async function fetchResults(q){showResults(q);resultsList.replaceChildren();resultError.hidden=true;resultStatus.textContent=`Searching for ${q}…`;fallbackLink.removeAttribute('target');fallbackLink.href=`?q=${encodeURIComponent(q)}`;let own=[],indexed=0;try{const d=await ventureResults(q);own=d.results||[];indexed=d.indexed||0}catch{}if(own.length){own.forEach(r=>resultsList.append(resultCard(r)));resultStatus.textContent=`About ${own.length} results · searching ${indexed.toLocaleString()} indexed pages`;return}resultStatus.textContent=indexed?`No match in Venture's ${indexed.toLocaleString()} pages · checking the web…`:'Checking the web…';try{const d=await fallbackResults(q),b=d.results||[];if(!b.length)throw 0;b.forEach(r=>resultsList.append(resultCard(r)));resultStatus.textContent=`Results for ${q} · web results provided by DuckDuckGo`;return}catch{}resultStatus.textContent=indexed?`No results found in ${indexed.toLocaleString()} indexed pages`:'No results found';resultError.hidden=false}
function runSearch(raw){const q=raw.trim();if(!q)return;if(looksLikeURL(q))return openDirectURL(q);const u=new URL(location.href);u.search='';u.searchParams.set('q',q);history.pushState({q},'',u);fetchResults(q)}
$('searchForm').onsubmit=e=>{e.preventDefault();runSearch(searchInput.value)};
$('resultsForm').onsubmit=e=>{e.preventDefault();runSearch(resultsInput.value)};
themeToggle.onclick=cycleTheme;if(resultsThemeToggle)resultsThemeToggle.onclick=cycleTheme;
$('settingsButton').onclick=()=>{newTabToggle.checked=state.newTab;settingsDialog.showModal()};
$('footerSettings').onclick=e=>{e.preventDefault();newTabToggle.checked=state.newTab;settingsDialog.showModal()};
newTabToggle.onchange=()=>{state.newTab=newTabToggle.checked;localStorage.setItem('venture.newTab',String(state.newTab))};
window.onpopstate=()=>{const q=new URLSearchParams(location.search).get('q');if(q)fetchResults(q);else{resultsView.hidden=true;homeView.hidden=false;document.title='Venture'}};
const media=matchMedia('(prefers-color-scheme: dark)');if(media.addEventListener)media.addEventListener('change',()=>{if(state.theme==='system')applyTheme()});
applyTheme();updateStats();setInterval(updateStats,30000);const q=new URLSearchParams(location.search).get('q');if(q)fetchResults(q);else searchInput.focus();
