const state={newTab:localStorage.getItem('venture.newTab')==='true',theme:localStorage.getItem('venture.theme')||'system'};
const $=id=>document.getElementById(id),homeView=$('homeView'),resultsView=$('resultsView'),searchForm=$('searchForm'),searchInput=$('searchInput'),resultsForm=$('resultsForm'),resultsInput=$('resultsInput'),resultsList=$('resultsList'),resultStatus=$('resultStatus'),resultError=$('resultError'),fallbackLink=$('fallbackLink'),themeToggle=$('themeToggle'),settingsDialog=$('settingsDialog'),newTabToggle=$('newTabToggle');
function applyTheme(){const dark=state.theme==='dark'||(state.theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.dataset.theme=dark?'dark':'light';themeToggle.textContent=dark?'☀':'◐'}
function cycleTheme(){state.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';localStorage.setItem('venture.theme',state.theme);applyTheme()}
function looksLikeURL(v){return /^[a-zA-Z][a-zA-Z\d+.-]*:\/\//.test(v)||/^(localhost|127\.0\.0\.1)(:\d+)?(\/.*)?$/.test(v)||/^[^\s]+\.[^\s]+(\/.*)?$/.test(v)}
function openDirectURL(v){let u=v;if(!/^[a-zA-Z][a-zA-Z\d+.-]*:\/\//.test(u))u=/^(localhost|127\.0\.0\.1)/.test(u)?`http://${u}`:`https://${u}`;location.href=u}
function showResults(q){homeView.hidden=true;resultsView.hidden=false;resultsInput.value=q;document.title=`${q} — Venture`}
function resultCard(r){const a=document.createElement('article');a.className='result-card';const l=document.createElement('a');l.href=r.url;if(state.newTab){l.target='_blank';l.rel='noopener noreferrer'}const d=document.createElement('div');d.className='result-domain';try{d.textContent=r.domain||new URL(r.url).hostname.replace(/^www\./,'')}catch{d.textContent=r.url}const t=document.createElement('h2');t.textContent=r.title||r.url;const s=document.createElement('p');s.textContent=r.description||'';l.append(d,t,s);a.append(l);return a}
async function ventureResults(q){const r=await fetch(`/api/search?q=${encodeURIComponent(q)}`);if(!r.ok)throw new Error(`Venture API ${r.status}`);return r.json()}
async function ddgBridge(q){const r=await fetch(`https://api.duckduckgo.com/?q=${encodeURIComponent(q)}&format=json&no_html=1&skip_disambig=1`);if(!r.ok)throw new Error(`DDG ${r.status}`);const d=await r.json(),out=[];if(d.AbstractURL&&(d.Heading||d.AbstractText))out.push({url:d.AbstractURL,title:d.Heading||q,description:d.AbstractText});const flat=x=>{for(const i of x||[]){if(i.Topics)flat(i.Topics);else if(i.FirstURL&&i.Text){const p=i.Text.split(' - ');out.push({url:i.FirstURL,title:p[0],description:p.slice(1).join(' - ')||i.Text})}}};flat(d.RelatedTopics);return [...new Map(out.map(x=>[x.url,x])).values()].slice(0,12)}
async function fetchResults(q){showResults(q);resultsList.replaceChildren();resultError.hidden=true;resultStatus.textContent=`Searching Venture for “${q}”…`;fallbackLink.href=`https://duckduckgo.com/?q=${encodeURIComponent(q)}`;let own=[];let indexed=0;try{const data=await ventureResults(q);own=data.results||[];indexed=data.indexed||0}catch(e){console.info('Venture local index unavailable',e)}if(own.length){own.forEach(r=>resultsList.append(resultCard(r)));resultStatus.textContent=`${own.length} result${own.length===1?'':'s'} from Venture's ${indexed.toLocaleString()}-page index`;return}try{const bridge=await ddgBridge(q);if(!bridge.length)throw new Error('No bridge results');bridge.forEach(r=>resultsList.append(resultCard(r)));resultStatus.textContent=indexed?`No match in Venture's ${indexed.toLocaleString()} indexed pages — showing temporary web fallback`:'Venture index is empty — showing temporary web fallback';}catch(e){console.error(e);resultStatus.textContent=indexed?`No match in Venture's ${indexed.toLocaleString()} indexed pages`:`Venture has no indexed results yet`;resultError.hidden=false}}
function runSearch(raw){const q=raw.trim();if(!q)return;if(looksLikeURL(q))return openDirectURL(q);const u=new URL(location.href);u.search='';u.searchParams.set('q',q);history.pushState({q},'',u);fetchResults(q)}
searchForm.addEventListener('submit',e=>{e.preventDefault();runSearch(searchInput.value)});resultsForm.addEventListener('submit',e=>{e.preventDefault();runSearch(resultsInput.value)});themeToggle.addEventListener('click',cycleTheme);$('settingsButton').addEventListener('click',()=>{newTabToggle.checked=state.newTab;settingsDialog.showModal()});$('footerSettings').addEventListener('click',e=>{e.preventDefault();newTabToggle.checked=state.newTab;settingsDialog.showModal()});newTabToggle.addEventListener('change',()=>{state.newTab=newTabToggle.checked;localStorage.setItem('venture.newTab',String(state.newTab))});matchMedia('(prefers-color-scheme: dark)').addEventListener('change',()=>{if(state.theme==='system')applyTheme()});window.addEventListener('popstate',()=>{const q=new URLSearchParams(location.search).get('q');if(q)fetchResults(q);else{resultsView.hidden=true;homeView.hidden=false;document.title='Venture'}});applyTheme();const initialQuery=new URLSearchParams(location.search).get('q');if(initialQuery)fetchResults(initialQuery);else searchInput.focus();
